// import React from 'react';
// import { Link } from "react-router-dom";

// const PageNotFound = () => {
//   return (
//     <div>
//       <span>404 Error Page Not Found</span><br/>
//       <Link to="/">Go Back</Link>
//     </div>
//   )
// }

// export default PageNotFound


// THIS FILE IS GENERATED BY CHATGPT. I'M GOING TO WRITE THIS ON MY OWN AT THE END OF THIS PROJECT!

import { useEffect, useRef } from "react";

export default function PageNotFound() {
  const frameRef = useRef();

  useEffect(() => {
    const chars = ".,-~:;=!*#$@";
    let A = 0, B = 0;
    const interval = setInterval(() => {
      const b = [];
      const z = [];
      let output = "";

      for (let k = 0; k < 1760; k++) {
        b[k] = k % 80 === 79 ? "\n" : " ";
        z[k] = 0;
      }

      for (let j = 0; j < 6.28; j += 0.07) {
        for (let i = 0; i < 6.28; i += 0.02) {
          const c = Math.sin(i),
            d = Math.cos(j),
            e = Math.sin(A),
            f = Math.sin(j),
            g = Math.cos(A),
            h = d + 2,
            D = 1 / (c * h * e + f * g + 5),
            l = Math.cos(i),
            m = Math.cos(B),
            n = Math.sin(B),
            t = c * h * g - f * e;
          const x = Math.floor(40 + 30 * D * (l * h * m - t * n)),
            y = Math.floor(12 + 15 * D * (l * h * n + t * m)),
            o = x + 80 * y;
          const N = Math.floor(
            8 * ((f * e - c * d * g) * m - c * d * e - f * g - l * d * n)
          );
          if (y < 22 && y > 0 && x > 0 && x < 79 && D > z[o]) {
            z[o] = D;
            b[o] = chars[N > 0 ? N : 0];
          }
        }
      }

      output = b.join("");
      if (frameRef.current) {
        frameRef.current.innerText = output;
      }
      A += 0.04;
      B += 0.02;
    }, 50);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <div>
        <pre ref={frameRef}></pre>
      </div>
    </>
  );
}
